### ISSUE TITLE
Pressing a key doesnt work.

### ISSUE THREAD

**Issue by gigachadUltraShaggy100X** [ArijanJ/miditoqwerty#5]
everytime i press a key in the application, nothing comes up. I tried different sets but nothing worked. Resetting my pc didn't help either. Is there any solutions?

**Comment by ArijanJ** [comment]
Hi, can you please attach a screenshot of what the GUI/application looks like for you when your piano is plugged in?

**Comment by ArijanJ** [comment]
Closing this issue in a day or two.
