### ISSUE TITLE
so many issuses 

### ISSUE THREAD

**Issue by Thecomplainer1** [ArijanJ/miditoqwerty#6]
There are many issues that i found i cant open it like seriously so many errors like MSVCP140.dll was not found VCRUNTIME140.dll was not found I tried reinstalling it and it didnt work

**Comment by ArijanJ** [comment]
Hi, thanks for opening this issue.

You can find out how to solve this here: https://github.com/ArijanJ/miditoqwerty/wiki/Troubleshooting#vcruntimexxxdll-is-missing

**Comment by Thecomplainer1** [comment]
Oh thank you! That was fast
